name: balanced
description: Balanced quality/speed (15-25 min total)
expected_time: 15-25 minutes

sfm:
  matching_method: retrieval
  global_extractor: netvlad
  extractor: disk
  matcher: disk-lightglue
  num_matched: 20
  camera_model: PINHOLE
  sfm_backend: glomap
  data_factor: 1

gsplat:
  subcommand: mcmc
  data_factor: 8
  max_steps: 30000
  eval_steps: [7000, 15000, 30000]
  save_ply: true
  batch_size: 1
  camera_model: pinhole
  antialiased: true

  strategy:
    cap_max: 1000000
    min_opacity: 0.005
    refine_start_iter: 500
    refine_stop_iter: 25000
    refine_every: 100
    verbose: true
